THEOS_DEVICE_IP = 192.168.99.209
ARCH = arm64

include /Users/dengjinlong/Documents/theos/makefiles/common.mk


TWEAK_NAME = WeChatFakeLocation
WeChatFakeLocation_FILES = Tweak.xm FakeWeChatLocationManager.m
WeChatFakeLocation_FRAMEWORKS = UIKit CoreLocation

include $(THEOS_MAKE_PATH)/tweak.mk
