git config --global alias.brname 'branch --show-current'
git config --global alias.pushmerge  'push -o merge_request.create -o merge_request.target=develop -o merge_request.remove_source_branch -o merge_request.description="/assign @laile.deng"'
git config --global alias.pushmergelocal '!f() { git pushmerge origin $(git brname):$(git brname); }; f'
git config --global alias.odpushlocal '!f() { git push origin $(git brname):$(git brname); }; f'
git config --global alias.odco 'checkout origin/develop -t -b'
git config --global alias.odpull '!f() { git fetch origin; git rebase origin/develop; }; f'
git config --global alias.odpush  '!f() { git odpull; git pushmergelocal; }; f'
git config --global alias.oddel '!f() { export ODBR=$(git brname); git checkout develop; git branch -d $ODBR; unset ODBR; }; f'
git config --global alias.odbugfix '!f() { if [ -n "$1" ];then git odco local/bugfix-$1;fi; }; f'
git config --global alias.odfeature '!f() { if [ -n "$1" ];then git odco local/feature-$1;fi; }; f'
